<?
session_start();
header('Content-Type: text/html; charset=utf-8');
require_once './../global.inc.php';
require_once '../a_cache/app_top.php';

$app_name='jccs';
setcookie('v_appname',$app_name, time()+3000, '/');
reset_appstatus ( $app_name );
$questionOptionList = array(
'1'=>array('question'=>'印度神油的功能是（ ）？',
		'answers'=>array(
				array('option'=>'A.炒饭', 'value'=>'2' ),
				array('option'=>'B.没听过', 'value'=>'3' ),
				array('option'=>'C.治风湿', 'value'=>'1' ),
				array('option'=>'D.能够与敌人大战几百回合', 'value'=>'0' ),
				)),
'2'=>array('question'=>'你觉得印度爱经是（ ）？',
		'answers'=>array(
				array('option'=>'A.动作指导书', 'value'=>'0' ),
				array('option'=>'B.言情小说', 'value'=>'1' ),
				array('option'=>'C.文学精选', 'value'=>'2' ),
				array('option'=>'D.经书', 'value'=>'3' ),
				)),
'3'=>array('question'=>'苍井空是谁（ ）？',
		'answers'=>array(
				array('option'=>'A.我的战友', 'value'=>'0' ),
				array('option'=>'B.德艺双馨的艺术家', 'value'=>'1' ),
				array('option'=>'C.我的老师', 'value'=>'2' ),
				array('option'=>'D.好像听过', 'value'=>'3' ),
				)),
'4'=>array('question'=>'一群女生到农场挤牛奶，别人已经挤了半筒，而小紫只挤了一点点，为什么（ ）？',
		'answers'=>array(
				array('option'=>'A.她不但挤错了牛，还挤错了地方', 'value'=>'0' ),
				array('option'=>'B.她力气不够', 'value'=>'2' ),
				array('option'=>'C.她挤的这头牛别人挤过了', 'value'=>'3' ),
				array('option'=>'D.她挤得是老牛', 'value'=>'1' ),
				)),
'5'=>array('question'=>'你是怎么来到这个世界上的（ ）？',
		'answers'=>array(
				array('option'=>'A.爱情的结晶', 'value'=>'3' ),
				array('option'=>'B.妈妈在垃圾桶捡的', 'value'=>'2' ),
				array('option'=>'C.都是爸爸不小心', 'value'=>'0' ),
				array('option'=>'D.石头里崩出来的', 'value'=>'1' ),
				)),
'6'=>array('question'=>'为什么最近“小三”那么红（ ）？',
		'answers'=>array(
				array('option'=>'A.人类进化的必然结果', 'value'=>'0' ),
				array('option'=>'B.这是一种潮流', 'value'=>'3' ),
				array('option'=>'C.这是一种新兴职业', 'value'=>'1' ),
				array('option'=>'D.因为三角形具有稳定性', 'value'=>'2' ),
				)),
'7'=>array('question'=>'你上班时候穿内裤吗（ ）？',
		'answers'=>array(
				array('option'=>'A.我也配穿内裤？', 'value'=>'0' ),
				array('option'=>'B.不上班', 'value'=>'2' ),
				array('option'=>'C.绝对不穿', 'value'=>'1' ),
				array('option'=>'D.穿', 'value'=>'3' ),
				)),
'8'=>array('question'=>' 两个男生牵手在街上走，他们的关系是（ ）？',
		'answers'=>array(
				array('option'=>'A.战友', 'value'=>'1' ),
				array('option'=>'B.同事', 'value'=>'2' ),
				array('option'=>'C.好哥们', 'value'=>'3' ),
				array('option'=>'D.情侣', 'value'=>'0' ),
				)),
'9'=>array('question'=>'法律规定男生只能娶一个太太，这条法律意在（ ）？',
		'answers'=>array(
				array('option'=>'A.毫无意义，建议废除', 'value'=>'1' ),
				array('option'=>'B.保证男人平均寿命', 'value'=>'3' ),
				array('option'=>'C.争风吃醋，有害社会', 'value'=>'0' ),
				array('option'=>'D.社会发展的客观要求', 'value'=>'2' ),
				)),
'10'=>array('question'=>'何谓“爱情动作片”（ ）？',
		'answers'=>array(
				array('option'=>'A.没听过', 'value'=>'3' ),
				array('option'=>'B.感人的爱情片', 'value'=>'2' ),
				array('option'=>'C.台词很少的日本片', 'value'=>'0' ),
				array('option'=>'D.教学片', 'value'=>'1' ),
				)),
'11'=>array('question'=>'植物大战僵尸里的一大波僵尸是什么意思（ ）？',
		'answers'=>array(
				array('option'=>'A.烫大波浪的僵尸 ', 'value'=>'1' ),
				array('option'=>'B.一大群僵尸', 'value'=>'3' ),
				array('option'=>'C.一群波很大的僵尸', 'value'=>'0' ),
				array('option'=>'D.没玩过介个', 'value'=>'2' ),
				)),
'12'=>array('question'=>'宅男为什么费纸（ ）？',
		'answers'=>array(
				array('option'=>'A.爱干净 ', 'value'=>'3' ),
				array('option'=>'B.看电视剧时经常被感动', 'value'=>'1' ),
				array('option'=>'C.都是种子的错', 'value'=>'0' ),
				array('option'=>'D.肠胃不好', 'value'=>'2' ),
				)),
'13'=>array('question'=>'近期最想做的事（ ）？',
		'answers'=>array(
				array('option'=>'A.让我去看3D肉蒲团！ ', 'value'=>'0' ),
				array('option'=>'B.涨工资', 'value'=>'3' ),
				array('option'=>'C.找到工作', 'value'=>'2' ),
				array('option'=>'D.找到对象', 'value'=>'1' ),
				)),
'14'=>array('question'=>'“菊花”一词为何走红（ ）？',
		'answers'=>array(
				array('option'=>'A.陶渊明的诗词 ', 'value'=>'3' ),
				array('option'=>'B.“菊花台”这首歌', 'value'=>'2' ),
				array('option'=>'C.象征纯洁', 'value'=>'1' ),
				array('option'=>'D.人体器官的形象化', 'value'=>'0' ),
				)),
'15'=>array('question'=>'哪个楼下的垃圾桶里，黄瓜和胡萝卜最多（ ）？',
		'answers'=>array(
				array('option'=>'A.菜市场', 'value'=>'3' ),
				array('option'=>'B.世贸大楼', 'value'=>'2' ),
				array('option'=>'C.女生宿舍楼', 'value'=>'0' ),
				array('option'=>'D.黄鹤楼', 'value'=>'1' ),
				)),
'16'=>array('question'=>'填空：每个男人都有一个___（ ）',
		'answers'=>array(
				array('option'=>'A.喉结', 'value'=>'1' ),
				array('option'=>'B.梦中情人', 'value'=>'2' ),
				array('option'=>'C.理想', 'value'=>'3' ),
				array('option'=>'D.小弟弟', 'value'=>'0' ),
				)),
'17'=>array('question'=>'你邀请女朋友去海里游泳，女朋友说会引来鲨鱼，为什么（ ）？',
		'answers'=>array(
				array('option'=>'A.她不喜欢我了', 'value'=>'1' ),
				array('option'=>'B.她姨妈来看她', 'value'=>'0' ),
				array('option'=>'C.她胆小', 'value'=>'2' ),
				array('option'=>'D.海里有鲨鱼', 'value'=>'3' ),
				)),
'18'=>array('question'=>'QQ上有人问你：我的头像牛B吗？你会回答（ ）？',
		'answers'=>array(
				array('option'=>'A.难看死了', 'value'=>'2' ),
				array('option'=>'B.像！', 'value'=>'1' ),
				array('option'=>'C.为什么是牛的？', 'value'=>'0' ),
				array('option'=>'D.牛B', 'value'=>'3' ),
				)),
'19'=>array('question'=>'据说男生都不喜欢娃娃，你觉得是这样吗（ ）？',
		'answers'=>array(
				array('option'=>'A.不是', 'value'=>'2' ),
				array('option'=>'B.不了解', 'value'=>'1' ),
				array('option'=>'C.只喜欢充气的', 'value'=>'0' ),
				array('option'=>'D.是的', 'value'=>'3' ),
				)),
'20'=>array('question'=>'你和朋友在一起，一般都干吗（ ）？',
		'answers'=>array(
				array('option'=>'A.逛街', 'value'=>'3' ),
				array('option'=>'B.“嗯”', 'value'=>'0' ),
				array('option'=>'C.聊天', 'value'=>'1' ),
				array('option'=>'D.看电影', 'value'=>'2' ),
				)),
'21'=>array('question'=>'夸一个女孩“事业线”很深是指（ ）？',
		'answers'=>array(
				array('option'=>'A.事业很好', 'value'=>'3' ),
				array('option'=>'B.胸部大', 'value'=>'0' ),
				array('option'=>'C.命好', 'value'=>'2' ),
				array('option'=>'D.心机重', 'value'=>'1' ),
				)),
'22'=>array('question'=>'为什么在小龙女跳崖后16年,杨过的左手就天下无敌了（ ）？',
		'answers'=>array(
				array('option'=>'A.上健身房了', 'value'=>'1' ),
				array('option'=>'B.他是左撇子', 'value'=>'2' ),
				array('option'=>'C.练就神功', 'value'=>'3' ),
				array('option'=>'D.他都自己来', 'value'=>'0' ),
				)),
'23'=>array('question'=>'在饭店询问服务员“服务员，有鸡吗？”你最可能听到的回答是（ ）？',
		'answers'=>array(
				array('option'=>'A.“我去厨房看看”', 'value'=>'1' ),
				array('option'=>'B.“卖完了”', 'value'=>'2' ),
				array('option'=>'C.“嘘，我就是！”', 'value'=>'0' ),
				array('option'=>'D.“有”', 'value'=>'3' ),
				)),
'24'=>array('question'=>'小明有三个女友，一个给他钱花、一个帮他挣钱、一个帮他省钱，他会选择（ ）？',
		'answers'=>array(
				array('option'=>'A.帮他省钱的', 'value'=>'2' ),
				array('option'=>'B.胸部最大的那一个', 'value'=>'0' ),
				array('option'=>'C.给他钱花的', 'value'=>'3' ),
				array('option'=>'D.帮他挣钱的', 'value'=>'1' ),
				)),
'25'=>array('question'=>'一女上厕所，正好没纸了，这时旁边有只手递了草纸给她，请问这只手是谁的（ ）？',
		'answers'=>array(
				array('option'=>'A.厕所女神', 'value'=>'2' ),
				array('option'=>'B.偷窥狂', 'value'=>'1' ),
				array('option'=>'C.好心人', 'value'=>'3' ),
				array('option'=>'D.厕所所长', 'value'=>'0' ),
				)),
'26'=>array('question'=>'老公最怕老婆说什么话（ ）？',
		'answers'=>array(
				array('option'=>'A.老公，我要……', 'value'=>'1' ),
				array('option'=>'B.老公，我还要……', 'value'=>'0' ),
				array('option'=>'C.老公，少喝酒', 'value'=>'3' ),
				array('option'=>'D.老公，工资上缴', 'value'=>'2' ),
				)),
'27'=>array('question'=>'拒绝别人爱意，你一般怎么表达（ ）？',
		'answers'=>array(
				array('option'=>'A.我配不上你', 'value'=>'2' ),
				array('option'=>'B.我有喜欢的人了', 'value'=>'3' ),
				array('option'=>'C.我们人鬼殊途……', 'value'=>'0' ),
				array('option'=>'D.喜欢我什么，我改！', 'value'=>'1' ),
				)),
'28'=>array('question'=>'你对一休哥的回忆还剩下什么（ ）？',
		'answers'=>array(
				array('option'=>'A.割鸡割鸡割鸡割鸡割鸡割鸡…', 'value'=>'0' ),
				array('option'=>'B.他妈妈是皇妃', 'value'=>'1' ),
				array('option'=>'C.小叶子是他的好朋友', 'value'=>'2' ),
				array('option'=>'D.他是光头', 'value'=>'3' ),
				)),
'29'=>array('question'=>'小明，谢谢你送我宝马战靴！“闹太套！！”问：小明姓什么（ ）？',
		'answers'=>array(
				array('option'=>'A.蓝', 'value'=>'1' ),
				array('option'=>'B.绿', 'value'=>'2' ),
				array('option'=>'C.红', 'value'=>'3' ),
				array('option'=>'D.黄', 'value'=>'0' ),
				)),
'30'=>array('question'=>'你从小到大最拿手的科目是（ ）？',
		'answers'=>array(
				array('option'=>'A.语文', 'value'=>'3' ),
				array('option'=>'B.没读过书', 'value'=>'1' ),
				array('option'=>'C.生物', 'value'=>'2' ),
				array('option'=>'D.生理课', 'value'=>'0' ),
				)),
'31'=>array('question'=>'一般电脑坏了，你会（ ）？',
		'answers'=>array(
				array('option'=>'A.不敢拿去店里修，会出名的', 'value'=>'0' ),
				array('option'=>'B.自己修', 'value'=>'3' ),
				array('option'=>'C.找朋友来修', 'value'=>'2' ),
				array('option'=>'D.咱再买一个吧', 'value'=>'1' ),
				)),
'32'=>array('question'=>'肯德基叔叔和麦当劳爷爷什么关系（ ）？',
		'answers'=>array(
				array('option'=>'A.经常吵架的情侣', 'value'=>'1' ),
				array('option'=>'B.好朋友', 'value'=>'0' ),
				array('option'=>'C.竞争对手', 'value'=>'3' ),
				array('option'=>'D.情敌', 'value'=>'2' ),
				)),
'33'=>array('question'=>'男人最痛苦的日子是哪天（ ）？',
		'answers'=>array(
				array('option'=>'A.十二月“一”日', 'value'=>'0' ),
				array('option'=>'B.一月“三十一”日', 'value'=>'1' ),
				array('option'=>'C.情人节', 'value'=>'2' ),
				array('option'=>'D.父亲节', 'value'=>'3' ),
				)),
'34'=>array('question'=>'在上届世界杯中日本以3:1的成绩大败丹麦队，对此你怎么看（ ）？',
		'answers'=>array(
				array('option'=>'A.太意外了', 'value'=>'3' ),
				array('option'=>'B.写童话果然搞不过拍片的', 'value'=>'0' ),
				array('option'=>'C.丹麦肿么了', 'value'=>'2' ),
				array('option'=>'D.对足球不了解', 'value'=>'1' ),
				)),
'35'=>array('question'=>'有一个人，想来就来，不想来就不来，不来急死你，来了烦死你。TA是（ ）？',
		'answers'=>array(
				array('option'=>'A. 房东', 'value'=>'2' ),
				array('option'=>'B.大姨妈', 'value'=>'0' ),
				array('option'=>'C.快递', 'value'=>'2' ),
				array('option'=>'D.大姑妈', 'value'=>'1' ),
				)),
'36'=>array('question'=>'你对“爱”有什么看法（ ）？',
		'answers'=>array(
				array('option'=>'A.看法是没有，做法倒是很多', 'value'=>'0' ),
				array('option'=>'B.爱不仅指爱情，更包括亲情、友情', 'value'=>'3' ),
				array('option'=>'C.爱是甜蜜的心有灵犀', 'value'=>'1' ),
				array('option'=>'D.爱是人间最美妙的语言', 'value'=>'2' ),
				)),
'37'=>array('question'=>'苍老师问你“有没有应到的未到”，你应该大声的回答TA（ ）',
		'answers'=>array(
				array('option'=>'A.有！', 'value'=>'1' ),
				array('option'=>'B.老师先让我数数！', 'value'=>'3' ),
				array('option'=>'C.没闻到！', 'value'=>'0' ),
				array('option'=>'D.没有！', 'value'=>'2' ),
				)),
'38'=>array('question'=>'蛇的交配时间是要持续12小时，对此你的看法（ ）？',
		'answers'=>array(
				array('option'=>'A.关我什么事', 'value'=>'3' ),
				array('option'=>'B.许仙真厉害', 'value'=>'1' ),
				array('option'=>'C.有空去试试', 'value'=>'0' ),
				array('option'=>'D.好久 ', 'value'=>'2' ),
				)),
'39'=>array('question'=>'烂掉的萝卜和怀孕的女人有什么相同点（ ）？',
		'answers'=>array(
				array('option'=>'A.尼玛 我生物不好', 'value'=>'2' ),
				array('option'=>'B.完全没有相同点', 'value'=>'3' ),
				array('option'=>'C.都是虫子惹的祸', 'value'=>'1' ),
				array('option'=>'D.拔晚了', 'value'=>'0' ),
				)),
'40'=>array('question'=>'为什么炮兵连炊事班战士是世界上最可怜的人（ ）？',
		'answers'=>array(
				array('option'=>'A.因为戴绿帽', 'value'=>'1' ),
				array('option'=>'B.因为背黑锅', 'value'=>'2' ),
				array('option'=>'C.天天煮饭很无聊的', 'value'=>'3' ),
				array('option'=>'D.因为整天看别人打炮 ', 'value'=>'0' ),
				)),
'41'=>array('question'=>'一男的和一女的只是握了握手，为什么那女的怀孕了（ ）？',
		'answers'=>array(
				array('option'=>'A.这不符合常理', 'value'=>'3' ),
				array('option'=>'B.希望砖家给予解释', 'value'=>'1' ),
				array('option'=>'C.这俩人都不洗手', 'value'=>'0' ),
				array('option'=>'D.握手也能怀孕？', 'value'=>'2' ),
				)),
'42'=>array('question'=>'“软”字的拼音怎么读（ ）？',
		'answers'=>array(
				array('option'=>'A.日完俺~软', 'value'=>'2' ),
				array('option'=>'B.日五晚，软', 'value'=>'1' ),
				array('option'=>'C.日五晚俺~软', 'value'=>'0' ),
				array('option'=>'D.日完~软', 'value'=>'3' ),
				)),
'43'=>array('question'=>'女人为啥要来大姨妈（ ）？',
		'answers'=>array(
				array('option'=>'A.大姨妈真讨厌', 'value'=>'2' ),
				array('option'=>'B.不来就惨了', 'value'=>'1' ),
				array('option'=>'C.生理问题', 'value'=>'3' ),
				array('option'=>'D.男人也要休息', 'value'=>'0' ),
				)),
'44'=>array('question'=>'为什么母系氏族人类住山洞，父系氏族人类住高楼（ ）？',
		'answers'=>array(
				array('option'=>'A.为了防蚊虫', 'value'=>'2' ),
				array('option'=>'B.高楼住着舒服', 'value'=>'3' ),
				array('option'=>'C.对那啥形象化的崇拜', 'value'=>'0' ),
				array('option'=>'D.技术在进步', 'value'=>'1' ),
				)),
'45'=>array('question'=>'你觉得快乐吗（ ）？',
		'answers'=>array(
				array('option'=>'A.快乐', 'value'=>'3' ),
				array('option'=>'B.我比较情绪化', 'value'=>'2' ),
				array('option'=>'C.快还能感觉到乐？', 'value'=>'0' ),
				array('option'=>'D.不快乐', 'value'=>'1' ),
				)),
'46'=>array('question'=>'如果没有白马王子，白雪公主会喜欢谁（ ）？',
		'answers'=>array(
				array('option'=>'A.七个小矮人', 'value'=>'1' ),
				array('option'=>'B.保持单身', 'value'=>'3' ),
				array('option'=>'C.时不时说谎的匹诺曹', 'value'=>'0' ),
				array('option'=>'D.史莱克', 'value'=>'2' ),
				)),
'47'=>array('question'=>'一美女洗澡后一丝不挂从浴室出来，家里小狗不停的跟在她后面。小狗想的是（ ）？',
		'answers'=>array(
				array('option'=>'A.不就两个肉包子吗，至于挂那么高吗', 'value'=>'0' ),
				array('option'=>'B.主人，好香~', 'value'=>'1' ),
				array('option'=>'C.主人，主人抱抱我', 'value'=>'3' ),
				array('option'=>'D.啧啧，穿下衣服会死？', 'value'=>'2' ),
				)),
'48'=>array('question'=>'副将请示将军是否乘胜追击，将军说了一句话同意追击，但大军未动？为什么（ ）？',
		'answers'=>array(
				array('option'=>'A.将军说：追击吧！', 'value'=>'0' ),
				array('option'=>'B.将军声音太小', 'value'=>'3' ),
				array('option'=>'C.大军叛变了', 'value'=>'1' ),
				array('option'=>'D.副将耳背', 'value'=>'2' ),
				)),
'49'=>array('question'=>'现在女孩的择友条件，哪个最重要（ ）？',
		'answers'=>array(
				array('option'=>'A.人好最重要', 'value'=>'3' ),
				array('option'=>'B.一米八', 'value'=>'2' ),
				array('option'=>'C.18CM', 'value'=>'0' ),
				array('option'=>'D.一百八十平方', 'value'=>'1' ),
				)),
'50'=>array('question'=>'渔夫捕了一条美人鱼，鱼尾巴以上是个超级美女，但是渔夫想了想把她放了，为什么（ ）？',
		'answers'=>array(
				array('option'=>'A.他海鲜过敏', 'value'=>'1' ),
				array('option'=>'B.养不起美人鱼', 'value'=>'2' ),
				array('option'=>'C.渔夫很善良', 'value'=>'3' ),
				array('option'=>'D.美人鱼的牙齿很利', 'value'=>'3' ),
				)),
'51'=>array('question'=>'你觉得为什么现在那么多独生子女（ ）？',
		'answers'=>array(
				array('option'=>'A.父母感情转淡', 'value'=>'1' ),
				array('option'=>'B.生太多养不起', 'value'=>'2' ),
				array('option'=>'C.响应国家政策', 'value'=>'3' ),
				array('option'=>'D.现在的小孩都太晚睡', 'value'=>'0' ),
				)),
'52'=>array('question'=>'有一个美丽的女孩。她每天刷5次牙，是为什么( )？',
		'answers'=>array(
				array('option'=>'A.火气大', 'value'=>'2' ),
				array('option'=>'B.讲卫生', 'value'=>'3' ),
				array('option'=>'C.她有很强壮的男朋友', 'value'=>'0' ),
				array('option'=>'D.她有洁癖', 'value'=>'1' ),
				)),
'53'=>array('question'=>'你觉得最邪恶的学科是（ ）？',
		'answers'=>array(
				array('option'=>'A.语文——停车做爱枫亭晚', 'value'=>'1' ),
				array('option'=>'B.政治——我是来打酱油的', 'value'=>'3' ),
				array('option'=>'C.生物——人体真内涵', 'value'=>'2' ),
				array('option'=>'D.数学——每次解题之前都要先“设”', 'value'=>'0' ),
				)),
'54'=>array('question'=>'什么卡通人物最专情（ ）？',
		'answers'=>array(
				array('option'=>'A.蜡笔小新（你猜猜）', 'value'=>'0' ),
				array('option'=>'B.一休哥（早已淡出红尘）', 'value'=>'1' ),
				array('option'=>'C.功夫熊猫（就知道吃）', 'value'=>'2' ),
				array('option'=>'D.美人鱼（因为她劈不了腿）', 'value'=>'3' ),
				)),
'55'=>array('question'=>'请用一句话总结香港娱乐圈（本题目纯属娱乐，请勿当真）（ ）？',
		'answers'=>array(
				array('option'=>'A.柏汁冠吸霆疯', 'value'=>'0' ),
				array('option'=>'B.和谐社会', 'value'=>'2' ),
				array('option'=>'C.关我屁事', 'value'=>'1' ),
				array('option'=>'D.好乱啊', 'value'=>'3' ),
				)),
'56'=>array('question'=>'妻子告诉丈夫她昨晚与自己的妹妹在一起留宿在外，丈夫坚信她撒谎，为什么（ ）？',
		'answers'=>array(
				array('option'=>'A.妻子神情闪烁', 'value'=>'3' ),
				array('option'=>'B.昨晚跟妻子妹妹在一起的是他', 'value'=>'0' ),
				array('option'=>'C.两女人有啥好KF的', 'value'=>'1' ),
				array('option'=>'D.妻子常常说谎', 'value'=>'2' ),
				)),
'57'=>array('question'=>'人生最痛苦的事莫过于（ ）？',
		'answers'=>array(
				array('option'=>'A.除了加班，跟加薪加爵都不熟', 'value'=>'2' ),
				array('option'=>'B.要好好活着，因为墓地涨价了', 'value'=>'1' ),
				array('option'=>'C.熬夜啃书也挡不住高考落榜', 'value'=>'3' ),
				array('option'=>'D.大醉而归，伸手一摸，贞操居然还在~！靠~！', 'value'=>'0' ),
				)),
'58'=>array('question'=>'小美在作文簿里写上长大後的愿望：一、我希望能有一个可爱的孩子；二、我还希望能有一个爱我的丈夫。可老师却让她重写，因为（ ）？',
		'answers'=>array(
				array('option'=>'A.没有表现当代女子独立自强的精神', 'value'=>'3' ),
				array('option'=>'B.太早熟了', 'value'=>'2' ),
				array('option'=>'C.请注意先后顺序', 'value'=>'1' ),
				array('option'=>'D.因为小美是男生', 'value'=>'0' ),
				)),
'59'=>array('question'=>'有两个男生同时追求一个女孩，女孩说谁先环游世界，我们就在一起。第一个男孩背起行囊准备启程，第二个男孩绕着女孩跑了一圈说：“YOU ARE MY WORLD。” 女孩最终选择（ ）？',
		'answers'=>array(
				array('option'=>'A.选择了比较有钱的那一个', 'value'=>'0' ),
				array('option'=>'B.第二男孩，浪漫大过天', 'value'=>'2' ),
				array('option'=>'C.无法选择，各有各的好啊', 'value'=>'1' ),
				array('option'=>'D.第一个男孩，用行动证明了自己', 'value'=>'3' ),
				)),
'60'=>array('question'=>'《人生的奥妙》有一段独白：“一大群精子向一个卵子冲去，跑得最有力的那个与卵子结合，形成受精卵，再经过9个月的怀胎，人诞生了。”从中你有何体会（ ）？',
		'answers'=>array(
				array('option'=>'A.我们都是胜利者', 'value'=>'0' ),
				array('option'=>'B.好复杂', 'value'=>'2' ),
				array('option'=>'C.真奇妙', 'value'=>'3' ),
				array('option'=>'D.竞争真激烈', 'value'=>'1' ),
				)),
'61'=>array('question'=>'关键字：野外、SM、人兽、5P、幼齿、制服、同志、亚洲无@码，打一部片名（ ）？',
		'answers'=>array(
				array('option'=>'A.日本教育片', 'value'=>'0' ),
				array('option'=>'B.葫芦娃', 'value'=>'2' ),
				array('option'=>'C.西游记', 'value'=>'3' ),
				array('option'=>'D.黑豹警长', 'value'=>'1' ),
				)),
'62'=>array('question'=>'能不能说出人身体上的一个器官，在适当的情况下会膨胀到原来的六倍（ ）？',
		'answers'=>array(
				array('option'=>'A.男性特有的某些器官 ', 'value'=>'0' ),
				array('option'=>'B.菊花，上大号时', 'value'=>'1' ),
				array('option'=>'C.鼻子，挖鼻孔时', 'value'=>'2' ),
				array('option'=>'D.瞳孔，在光线微弱时', 'value'=>'3' ),
				)),
'63'=>array('question'=>'初出茅庐的意思（ ）？',
		'answers'=>array(
				array('option'=>'A.第一次走出草屋', 'value'=>'1' ),
				array('option'=>'B.刚出道', 'value'=>'3' ),
				array('option'=>'C.刚从宿舍出来', 'value'=>'2' ),
				array('option'=>'D.刚上完厕所 ', 'value'=>'0' ),
				)),
'64'=>array('question'=>'现在女生都怎么了，上半身穿棉袄，下半身穿丝袜（ ）？',
		'answers'=>array(
				array('option'=>'A.鲜奶要保温，火腿要冷藏', 'value'=>'2' ),
				array('option'=>'B.奶疼乳酸啊', 'value'=>'1' ),
				array('option'=>'C.时尚', 'value'=>'3' ),
				array('option'=>'D.有些地方需要风干 ', 'value'=>'0' ),
				)),
'65'=>array('question'=>'某晚，一裸男叫了一辆出租车，女司机目不转睛盯着看他，你觉得是因为（ ）？',
		'answers'=>array(
				array('option'=>'A.没见过裸男打的', 'value'=>'3' ),
				array('option'=>'B.裸男身材好', 'value'=>'0' ),
				array('option'=>'C.在想他等会从哪掏钱 ', 'value'=>'2' ),
				array('option'=>'D.女司机很色', 'value'=>'1' ),
				)),
'66'=>array('question'=>'男女朋友睡一个房间，女的画了条线说：“过线的是禽兽。”醒来发现男的真的没过线，女的还是狠狠的打了男的一巴掌，为什么（ ）？',
		'answers'=>array(
				array('option'=>'A.觉得自己没有魅力，很丢脸  ', 'value'=>'3' ),
				array('option'=>'B.此男连禽兽都不如', 'value'=>'0' ),
				array('option'=>'C.其实男生昨晚偷偷过线了', 'value'=>'2' ),
				array('option'=>'D.觉得他是GAY', 'value'=>'1' ),
				)),
'67'=>array('question'=>'女：你到底打算跟我结婚吗？男的沉默。女：别以为没人要我，搞火了我马上就在这找个人嫁了！这时，侍应生走过来说：（ ）',
		'answers'=>array(
				array('option'=>'A.请不要把客人全吓跑了', 'value'=>'0' ),
				array('option'=>'B.我娶你', 'value'=>'1' ),
				array('option'=>'C.冷静点', 'value'=>'3' ),
				array('option'=>'D.我报名', 'value'=>'2' ),
				)),
'68'=>array('question'=>'女：“我需要一个男友。”男：“我帮你找，我宿舍有个兄弟还不错。”女：“我跟他在一起，你不会心疼吗？”请假设男生将会如何回答（ ）？',
		'answers'=>array(
				array('option'=>'A.“别逗了，我还没心疼他呢”', 'value'=>'1' ),
				array('option'=>'B.“虽然我喜欢你，但是你们更相配”', 'value'=>'2' ),
				array('option'=>'C.“微小说看多了吧？我跟他没什么的，你放心好了。”', 'value'=>'0' ),
				array('option'=>'D.“不会的，我兄弟是个好人”', 'value'=>'3' ),
				)),
'69'=>array('question'=>'小淼、小鑫和小晶三个人是好朋友，小淼说他取这个名字是因为五行缺水，小鑫说他取这个名字是因为五行缺金，小晶听完生气的走了，WHY（ ）？',
		'answers'=>array(
				array('option'=>'A.他们太迷信了，鄙视之', 'value'=>'3' ),
				array('option'=>'B.吃坏东西，赶着拉肚子', 'value'=>'2' ),
				array('option'=>'C.他俩搞暧昧，小晶受不了', 'value'=>'1' ),
				array('option'=>'D.小晶想到了自己的名字……', 'value'=>'0' ),
				)),
'70'=>array('question'=>'一个小伙子常到一个总是满客理发店问理发师还要等多久，问完就离开，从没回来过，这是为什么（ ）？',
		'answers'=>array(
				array('option'=>'A.他是傻子', 'value'=>'2' ),
				array('option'=>'B.他不想等', 'value'=>'3' ),
				array('option'=>'C.他离开后去了理发师的家……', 'value'=>'0' ),
				array('option'=>'D.他是别家理发店的卧底 ', 'value'=>'1' ),
				)),
'71'=>array('question'=>'有个人出门找茬，到处叫嚣，“谁敢惹我？” 结果一个壮汉一把拦住，“我敢”。请为他想一个方法让他自救 （ ）。',
		'answers'=>array(
				array('option'=>'A.跳到壮汉身边，大声说“谁敢惹咱俩！”', 'value'=>'1' ),
				array('option'=>'B.跪地求饶', 'value'=>'3' ),
				array('option'=>'C.主动奉上身上全部财物', 'value'=>'2' ),
				array('option'=>'D.“菊花台，满地伤，你的笑容已泛黄”', 'value'=>'0' ),
				)),
'72'=>array('question'=>'小明试着用手机给女朋友发一张他小弟弟的照片，结果没发成功并提示原因，小明看后却心情很好，为什么（ ）？',
		'answers'=>array(
				array('option'=>'A.提示“图片过大，可能无法传送”', 'value'=>'0' ),
				array('option'=>'B.提示“对不起，您的电话已欠费”', 'value'=>'3' ),
				array('option'=>'C.提示“对不起，您发送的用户已结婚。”', 'value'=>'1' ),
				array('option'=>'D.提示“您发送的图片已和谐”', 'value'=>'2' ),
				)),
'73'=>array('question'=>'毕业前夕，某男生对全班男同学进行一项问卷调查，题目只有一道：“大家都上过小学吗?”结果第二天这名男生就被开除了……WHY（ ）？',
		'answers'=>array(
				array('option'=>'A.这男生瞧不起人 ', 'value'=>'3' ),
				array('option'=>'B.他班有个女生名叫小学', 'value'=>'0' ),
				array('option'=>'C.他问问题没水准', 'value'=>'1' ),
				array('option'=>'D.他挂科了', 'value'=>'2' ),
				)),
'74'=>array('question'=>'抢匪：“快把保险箱密码说出来！不说杀了你！” 女职员：“杀了我也不说！你糟蹋了我我也不说！” 抢匪上下打量她后，厉声道：（ ）？',
		'answers'=>array(
				array('option'=>'A.我只喜欢异性', 'value'=>'2' ),
				array('option'=>'B.真是烈女', 'value'=>'3' ),
				array('option'=>'C.我只喜欢同性', 'value'=>'1' ),
				array('option'=>'D.你想得美！', 'value'=>'0' ),
				)),
'76'=>array('question'=>'少林寺的藏经阁失火了，方丈不禁失声痛哭起来……小和尚便问了起来：“方丈何患难忍啊？”方丈继续哭曰：（ ）',
		'answers'=>array(
				array('option'=>'A.以后晚上怎么撸啊！', 'value'=>'0' ),
				array('option'=>'B.都是用钱买的啊！', 'value'=>'3' ),
				array('option'=>'C.都是珍藏版啊！', 'value'=>'2' ),
				array('option'=>'D.老衲痛经啊……', 'value'=>'1' ),
				)),
'77'=>array('question'=>'避孕套和降落伞的区别是什么（ ）？',
		'answers'=>array(
				array('option'=>'A.一个保护上头一个保护下头', 'value'=>'1' ),
				array('option'=>'B.材质不同', 'value'=>'2' ),
				array('option'=>'C.降落伞破了少一个人，避孕套破了多一个人 ', 'value'=>'0' ),
				array('option'=>'D.一大一小', 'value'=>'3' ),
				)),
'78'=>array('question'=>'“小明，一起去打篮球啊？”“额，我，我不去了，我还要写小说。”请问：小明的身高是多少（ ）？',
		'answers'=>array(
				array('option'=>'A.一米七', 'value'=>'2' ),
				array('option'=>'B.两米二六', 'value'=>'1' ),
				array('option'=>'C.一米四二！', 'value'=>'0' ),
				array('option'=>'D.不知道', 'value'=>'3' ),
				)),
'79'=>array('question'=>'小芳：“你妹啊，老娘这个月大姨妈还没来，愁死姐了，简直就是坑爹啊！”问：短文中谁很着急（ ）？',
		'answers'=>array(
				array('option'=>'A.小芳她爹', 'value'=>'1' ),
				array('option'=>'B.小芳', 'value'=>'2' ),
				array('option'=>'C.小芳她老娘', 'value'=>'3' ),
				array('option'=>'D.小芳她姐姐', 'value'=>'0' ),
				)),
'80'=>array('question'=>'女人夏天穿BRA，不热吗（ ）？',
		'answers'=>array(
				array('option'=>'A.不热', 'value'=>'1' ),
				array('option'=>'B.不穿男人就热', 'value'=>'0' ),
				array('option'=>'C.热', 'value'=>'3' ),
				array('option'=>'D.BRA是什么', 'value'=>'2' ),
				)),
);
$randList = array_rand($questionOptionList, 5);
$questionAnswerList = array();
foreach ($randList as $ak) {
	$questionAnswerList[] = $questionOptionList[$ak];
}
if (is_mobile()) {
	require_once './../a_include/question_test_mobile.php';
} else {
	require_once './../a_include/question_test.php';
}
?>